CREATE DATABASE HRDB;
USE hrdb;

CREATE TABLE DEPARTMENTS (ID INT  PRIMARY KEY IDENTITY, NAME VARCHAR(MAX));
CREATE TABLE EMPLOYEES (ID INT PRIMARY KEY IDENTITY, NAME VARCHAR(MAX),  
EMAIL VARCHAR(MAX),GENDER VARCHAR(20),MOBILE VARCHAR (20), 
DEPARTMENT_ID INT FOREIGN KEY REFERENCES DEPARTMENTS(ID));


SELECT*FROM DEPARTMENTS
SELECT*FROM EMPLOYEES

CREATE PROC SP_DEPARTMENT
@action varchar(20),
@ID INT=0 ,
@NAME VARCHAR(100)=NULL
as
begin
if (@action='CREATE')
BEGIN
    INSERT INTO DEPARTMENTS(NAME) VALUES (@NAME)
	SELECT 1 AS RESULT
END
	ELSE IF(@action ='DELETE')
	BEGIN
	DELETE FROM DEPARTMENTS WHERE ID=@ID
	SELECT 1 AS RESULT
	END
ELSE IF (@action='SELECT')
BEGIN
SELECT*FROM DEPARTMENTS
SELECT 1 AS RESULT
END
ELSE IF (@action='UPDATE')
BEGIN
UPDATE DEPARTMENTS SET  NAME=@NAME WHERE ID=@ID
SELECT 1 AS RESULT
END
END


EXEC SP_DEPARTMENT 'SELECT'

EXEC SP_DEPARTMENT 'CREATE',0,'MARKETING';

EXEC SP_DEPARTMENT 'UPDATE',1,'MARKETING';
EXEC SP_DEPARTMENT 'DELETE',1







CREATE PROC SP_EMPLOYEE
@action varchar(20),
@ID INT=0 ,
@NAME VARCHAR(100)=NULL,
@EMAIL VARCHAR (100)=NULL,
@GENDER VARCHAR(15)=NULL,
@MOBILE VARCHAR (20)=NULL,
@DEPARTMENT_ID INT =0

as
begin
if (@action='CREATE')
BEGIN
    INSERT INTO EMPLOYEES(NAME,EMAIL,GENDER,MOBILE,DEPARTMENT_ID) VALUES (@NAME,@EMAIL,@GENDER,@MOBILE,@DEPARTMENT_ID)
	SELECT 1 AS RESULT
END
	ELSE IF(@action ='DELETE')
	BEGIN
	DELETE FROM EMPLOYEES WHERE ID=@ID
	SELECT 1 AS RESULT
	END
ELSE IF (@action='SELECT')
BEGIN
SELECT*FROM EMPLOYEES
SELECT 1 AS RESULT
END

ELSE IF (@action='SELECT_JOIN')
BEGIN
SELECT E.ID,E.NAME,E.EMAIL,E.MOBILE,E.GENDER,D.NAME FROM EMPLOYEES E
FULL OUTER JOIN
DEPARTMENTS D
ON E.DEPARTMENT_ID=D.ID
SELECT 1 AS RESULT
END

ELSE IF (@action='UPDATE')
BEGIN
UPDATE EMPLOYEES SET  NAME=@NAME,EMAIL=@EMAIL,GENDER=@GENDER,MOBILE=@MOBILE,DEPARTMENT_ID=@DEPARTMENT_ID WHERE ID=@ID
SELECT 1 AS RESULT
END
END



exec SP_EMPLOYEE 'SELECT';
exec SP_EMPLOYEE 'CREATE',0,'robert','robert55@gmail.com','male','4402261700',1;
exec SP_EMPLOYEE 'CREATE',0,'baba','baba55@gmail.com','male','5502261700',1;
exec SP_EMPLOYEE 'DELETE',4;

exec SP_EMPLOYEE 'SELECT_JOIN'


SELECT*FROM DEPARTMENTS
SELECT*FROM EMPLOYEES


ALTER PROC SP_EMPLOYEE
@action varchar(20),
@ID INT=0 ,
@NAME VARCHAR(100)=NULL,
@EMAIL VARCHAR (100)=NULL,
@GENDER VARCHAR(15)=NULL,
@MOBILE VARCHAR (20)=NULL,
@DEPARTMENT_ID INT =0

as
begin
if (@action='CREATE')
BEGIN
    INSERT INTO EMPLOYEES(NAME,EMAIL,GENDER,MOBILE,DEPARTMENT_ID) VALUES (@NAME,@EMAIL,@GENDER,@MOBILE,@DEPARTMENT_ID)
	SELECT 1 AS RESULT
END
	ELSE IF(@action ='DELETE')
	BEGIN
	DELETE FROM EMPLOYEES WHERE ID=@ID
	SELECT 1 AS RESULT
	END
ELSE IF (@action='SELECT')
BEGIN
SELECT*FROM EMPLOYEES
SELECT 1 AS RESULT
END

ELSE IF (@action='SELECT_JOIN')
BEGIN
SELECT E.ID,E.NAME,E.EMAIL,E.MOBILE,E.GENDER,D.NAME as department FROM EMPLOYEES E
FULL OUTER JOIN
DEPARTMENTS D
ON E.DEPARTMENT_ID=D.ID
SELECT 1 AS RESULT
END
END


exec SP_EMPLOYEE 'SELECT_JOIN';
